name: requests-adal-auth

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO: ${{secrets.DOCKER_REPO}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: yaananth/twine-upload@v1
    - name: List environment info
      run: |
        make info
    - name: Ensure code quality
      run: |
        make code-quality
    - name: Test code
      run: |
        make test
    - name: Build code
      run: |
        make build
    - name: Package for PyPi
      run: |
        make pack
    - name: Push version to PyPi
      run: |
        make push
