name: requests-adal-auth

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO: ${{secrets.DOCKER_REPO}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
        exclude:
         - os: macos-latest
           python-version: 3.8
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: List environment info
      run: |
        python -c "import sys; print(sys.version)"
        make info
    - name: Prepare environment
      run: |
        make prep
    - name: Ensure code quality
      run: |
        make code-quality
    - name: Test code
      run: |
        make test
    - name: Build code
      run: |
        make build
    - name: Package for PyPi
      run: |
        make pack
    - name: Push version to PyPi
      run: |
        make push
